version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ksh147!!  
      MYSQL_DATABASE: catcat  
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL 데이터 유지
      - ./initdb:/docker-entrypoint-initdb.d  # 초기화 SQL 적용
    networks:
      - app_network

  backend:
    image: ddukio/backend:latest
    container_name: backend
    depends_on:
      - mysql
    environment:
      # MySQL 컨테이너 이름을 호스트명으로 사용
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catcat?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ksh147!!
    ports:
      - "8080:8080"
    networks:
      - app_network

  frontend:
    image: ddukio/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"  # 외부 5173번 -> 컨테이너 내부 80번
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
