version: '3.8'

services:
  mysql:
  image: mysql:8.0
  container_name: mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: ksh147!!
    MYSQL_DATABASE: catcat
  ports:
    - "3307:3306"  # 호스트 3307, 컨테이너 3306
  volumes:
    - mysql_data:/var/lib/mysql
  networks:
    - app_network

  backend:
    image: ddukio/backend:latest
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catcat?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ksh147!!
    ports:
      - "8080:8080"
    networks:
      - app_network

  frontend:
    image: ddukio/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"  # 외부 포트 80 → 컨테이너 내부 포트 80
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
