version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ksh147!!
      MYSQL_DATABASE: catcat
    ports:
      - "3307:3306" # 호스트 3307 -> 컨테이너 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    image: ddukio/backend:latest
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catcat?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ksh147!!
    # 외부 노출을 막기 위해 ports 섹션 제거
    networks:
      - app_network

  frontend:
    image: ddukio/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    # Nginx가 외부 접속을 처리하므로, 직접 포트를 노출하지 않음
    networks:
      - app_network
    volumes:
      - /etc/letsencrypt/live/j12c107.p.ssafy.io/fullchain.pem:/etc/letsencrypt/live/j12c107.p.ssafy.io/fullchain.pem:ro
      - /etc/letsencrypt/live/j12c107.p.ssafy.io/privkey.pem:/etc/letsencrypt/live/j12c107.p.ssafy.io/privkey.pem:ro

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
