export default function getCardColor(category) {
    switch (category) {
        case "대중교통": return "#007bff"; // 파란색 (교통)
        case "캐시백": return "#28a745"; // 녹색 (절약/혜택)
        case "기타": return "#6c757d"; // 회색 (기타)
        case "해외": return "#17a2b8"; // 청록색 (여행)
        case "카페": return "#d2691e"; // 브라운 (커피)
        case "게임": return "#8a2be2"; // 보라색 (게임)
        case "공연/전시": return "#ff4500"; // 주황색 (문화)
        case "드럭스토어": return "#ff69b4"; // 핑크 (건강/미용)
        case "편의점": return "#32cd32"; // 연두색 (생활)
        case "디지털구독": return "#ff8c00"; // 주황색 (디지털)
        case "배달앱": return "#dc3545"; // 빨간색 (배달)
        case "통신": return "#20c997"; // 청록색 (통신)
        case "영화": return "#ffc107"; // 노란색 (영화)
        case "테마파크": return "#ff6347"; // 토마토색 (놀이공원)
        case "간편결제": return "#6f42c1"; // 보라색 (결제)
        case "적립": return "#198754"; // 초록색 (적립)
        case "생활": return "#007bff"; // 파란색 (생활)
        case "주유소": return "#ff4500"; // 주황색 (주유)
        case "택시": return "#ffc107"; // 노란색 (택시)
        case "카카오페이": return "#ffdd00"; // 노란색 (카카오페이)
        case "프리미엄 서비스": return "#b8860b"; // 금색 (프리미엄)
        case "온라인쇼핑": return "#ff1493"; // 핑크색 (쇼핑)
        case "해외이용": return "#20c997"; // 청록색 (여행)
        case "모든가맹점": return "#343a40"; // 검은색 (일반)
        case "푸드": return "#ff4500"; // 주황색 (음식)
        case "패스트푸드": return "#ff6347"; // 토마토색 (패스트푸드)
        case "혜택 프로모션": return "#ff69b4"; // 핑크색 (혜택)
        case "여행/숙박": return "#007bff"; // 파란색 (여행)
        case "금융": return "#008080"; // 청록색 (금융)
        case "도서": return "#8b4513"; // 갈색 (책)
        case "소셜커머스": return "#e83e8c"; // 진한 핑크 (소셜)
        case "교통": return "#17a2b8"; // 청록색 (교통)
        case "애완동물": return "#ff8c00"; // 주황색 (애완동물)
        case "네이버페이": return "#03c75a"; // 네이버 그린 (네이버페이)
        case "공항라운지": return "#4682b4"; // 스틸 블루 (공항)
        case "수수료우대": return "#6f42c1"; // 보라색 (혜택)
        case "할인": return "#ff0000"; // 빨간색 (할인)
        case "베이커리": return "#d2691e"; // 브라운 (빵)
        case "기차": return "#007bff"; // 파란색 (기차)
        case "고속버스": return "#dc3545"; // 빨간색 (버스)
        case "자동차": return "#6c757d"; // 회색 (자동차)
        case "OTT/영화/문화": return "#ff4500"; // 주황색 (문화)
        case "멤버십포인트": return "#ff69b4"; // 핑크색 (포인트)
        case "국내외가맹점": return "#343a40"; // 검은색 (일반)
        case "공과금/렌탈": return "#20c997"; // 청록색 (공과금)
        case "정비": return "#6c757d"; // 회색 (자동차 정비)
        case "렌터카": return "#6c757d"; // 회색 (렌터카)
        case "백화점": return "#800080"; // 보라색 (백화점)
        case "패밀리레스토랑": return "#ff4500"; // 주황색 (레스토랑)
        case "해피포인트": return "#ff69b4"; // 핑크색 (포인트)
        case "쇼핑": return "#ff1493"; // 핑크색 (쇼핑)
        case "뷰티/피트니스": return "#ff69b4"; // 핑크색 (미용)
        case "은행사": return "#008080"; // 청록색 (은행)
        case "무실적": return "#6c757d"; // 회색 (무실적)
        case "교육/육아": return "#ff8c00"; // 주황색 (교육)
        case "음원사이트": return "#ff4500"; // 주황색 (음악)
        case "APP": return "#6f42c1"; // 보라색 (앱)
        case "카페/디저트": return "#d2691e"; // 브라운 (디저트)
        case "대형마트": return "#ff1493"; // 핑크색 (마트)
        case "주유": return "#ff4500"; // 주황색 (주유)
        case "바우처": return "#ff6347"; // 토마토색 (바우처)
        case "공항라운지/PP": return "#4682b4"; // 스틸 블루 (공항)
        case "레저/스포츠": return "#ff4500"; // 주황색 (스포츠)
        case "골프": return "#228b22"; // 녹색 (골프)
        case "보험사": return "#6c757d"; // 회색 (보험)
        case "SSM": return "#32cd32"; // 연두색 (SSM)
        case "화장품": return "#ff69b4"; // 핑크색 (화장품)
        case "병원/약국": return "#20c997"; // 청록색 (병원)
        case "학원": return "#ff8c00"; // 주황색 (학원)
        case "비즈니스": return "#6c757d"; // 회색 (비즈니스)
        case "하이패스": return "#007bff"; // 파란색 (하이패스)
        case "대한항공": return "#4682b4"; // 스틸 블루 (항공)
        case "하이브리드": return "#6c757d"; // 회색 (하이브리드)
        case "OK캐쉬백": return "#ff69b4"; // 핑크색 (포인트)
        case "점심": return "#ff4500"; // 주황색 (음식)
        case "공과금": return "#20c997"; // 청록색 (공과금)
        case "헤어": return "#ff69b4"; // 핑크색 (미용)
        case "일반음식점": return "#ff4500"; // 주황색 (음식)
        case "마트/편의점": return "#32cd32"; // 연두색 (생활)
        case "해외직구": return "#17a2b8"; // 청록색 (해외)
        default: return "#6c757d"; // 기본 회색
    }
}